# Generated by Django 5.2.4 on 2025-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about yourself (max 500 characters)', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+1', 'United States (+1)'), ('+44', 'United Kingdom (+44)'), ('+33', 'France (+33)'), ('+49', 'Germany (+49)'), ('+234', 'Nigeria (+234)'), ('+233', 'Ghana (+233)'), ('+27', 'South Africa (+27)'), ('+254', 'Kenya (+254)'), ('+256', 'Uganda (+256)'), ('+39', 'Italy (+39)'), ('+34', 'Spain (+34)'), ('+31', 'Netherlands (+31)'), ('+32', 'Belgium (+32)'), ('+41', 'Switzerland (+41)'), ('+43', 'Austria (+43)'), ('+45', 'Denmark (+45)'), ('+46', 'Sweden (+46)'), ('+47', 'Norway (+47)'), ('+358', 'Finland (+358)'), ('+30', 'Greece (+30)'), ('+48', 'Poland (+48)'), ('+420', 'Czech Republic (+420)'), ('+36', 'Hungary (+36)'), ('+40', 'Romania (+40)'), ('+359', 'Bulgaria (+359)'), ('+385', 'Croatia (+385)'), ('+381', 'Serbia (+381)'), ('+355', 'Albania (+355)'), ('+386', 'Slovenia (+386)'), ('+389', 'North Macedonia (+389)'), ('+61', 'Australia (+61)'), ('+64', 'New Zealand (+64)'), ('+65', 'Singapore (+65)'), ('+60', 'Malaysia (+60)'), ('+62', 'Indonesia (+62)'), ('+63', 'Philippines (+63)'), ('+66', 'Thailand (+66)'), ('+84', 'Vietnam (+84)'), ('+81', 'Japan (+81)'), ('+82', 'South Korea (+82)'), ('+86', 'China (+86)'), ('+91', 'India (+91)'), ('+92', 'Pakistan (+92)'), ('+880', 'Bangladesh (+880)'), ('+966', 'Saudi Arabia (+966)'), ('+971', 'United Arab Emirates (+971)'), ('+20', 'Egypt (+20)'), ('+212', 'Morocco (+212)'), ('+55', 'Brazil (+55)'), ('+56', 'Chile (+56)'), ('+57', 'Colombia (+57)'), ('+51', 'Peru (+51)'), ('+54', 'Argentina (+54)'), ('+598', 'Uruguay (+598)')], default='+233', help_text='Country code for phone number', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Your date of birth', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, help_text='Your occupation or job title', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number without country code', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a clear profile picture (PNG or JPG, max 5MB)', null=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
